server:
  port: 8080

spring:
  # JDBC config
  datasource:
    url:  jdbc:postgresql://localhost:5432/hunter_db
    username: hunter_user
    password: hunter_pass
  # JPA config
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  # Liquibase config
  liquibase:
    change-log: classpath:db/liquibase-changelog.yaml
    enabled: true

map-spot-info-hunter:
  app:
    jwtSecret: mapSpotInfoHunterSecretKey
    jwtExpiration: 86400

google:
  maps:
    apiKey: AIzaSyCjhz1msYO5dhUHUiUfnE7MaYLy3cynL6w

openweathermap:
  apiKey: 1f3b610f0722a45b54db4a825627551a